config/routes.rb
Rails.application.routes.draw do
  get 'categories/destroy'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "stores/new", to: "stores#new"
  post "stores", to: "stores#create"
  get "stores", to: "stores#index"
  get "stores/:id", to: "stores#show", as: "store"
  get "stores/:id/edit", to: "stores#edit", as: "edit"
  patch "stores/:id", to: "stores#update"
  delete "stores/:id", to: "stores#destroy", as: "destroy_store"

  get "categories/new", to: "categories#new"
  post "categories/new", to: "categories#create"
  get "categories", to: "categories#index"
  get "categories/:id", to: "categories#show", as: "category"
  get "categories/:id/edit", to: "categories#edit", as: "categories_edit"
  post "categories/:id/edit", to: "categories#update"
  delete "categories/:id", to: "categories#destroy", as: "destroy_categories"

  get "items/new", to: "items#new"
  post "items", to: "items#create"
  get "items", to: "items#index"
  get "items/:id", to: "items#show", as: "item"
  get "items/:id/edit", to: "items#edit", as: "edit_item"
  patch "items/:id", to: "items#update" 
  delete "items/:id", to: "items#destroy", as: "destroy_item"

  post "items/:id/buy", to: "items#buy", as: "buy"
  get "items/:id/success", to: "items#success", as: "success"
  get "items/:id/cancel", to: "items#cancel", as: "cancel"


  root to: "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, numericality: {greater_than_or_equal_to: 1}
  validates :title, presence: true

  belongs_to :store
  belongs_to :category

  has_one_attached :image

  self.per_page = 8
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/store.rb
class Store < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :store
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @items = @category.items.paginate(:page => params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.create(name: params[:name])
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    category.update(name: params[:name])
    category.save
    redirect_to categories_path
  end
  
  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to categories_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
skip_before_action :verify_authenticity_token, only: [:buy]
before_action :set_item, only: [:buy, :edit]
before_action :authenticate_user!, only: [:new]

    def index
        @items = Item.paginate(:page => params[:page])
    end
    
    def new
        @item = Item.new
    end

    def create
        item = Item.new(item_params)
        item.store_id = current_user.store.id
        # item.image.attach(params[:image])
        item.save!
        redirect_to items_path
    end

    def show
        @item = Item.find(params[:id])
    end

    def edit
        
    end

    def update
        item = Item.find(params[:id])
        item.update(item_params)
        redirect_to item_path(item.id)
    end

    def destroy
        Item.destroy(params[:id])
        redirect_to items_path
    end

    def buy
        Stripe.api_key = ENV['STRIPE_API_KEY']
        session = Stripe::Checkout::Session.create({
            payment_method_types: ['card'],
            mode: 'payment',
            success_url: success_url(params[:id]),
            cancel_url: cancel_url(params[:id]),
            line_items: [{
                price_data: {
                    currency: 'aud',
                    product_data: {
                        name: @item.title
                    },
                    unit_amount: (@item.price * 100).to_i
                },
                quantity: 1
            }]
        })

        render json: session
    end

    def success
        # render plain: "Success!"
    end

    def cancel
        # render plain: "The transaction was cancelled."
    end


    private

    def item_params
        params.require(:item).permit(:title, :price, :category_id, :description, :image)
    end

    def set_item
        @item = Item.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        redirect_to items_path
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :authenticate_user!, except: [:index]
    
    def index
        @stores = Store.all
    end

    def new
        @store = Store.new
    end

    def create
        store = Store.new(store_params)
        store.user_id = current_user.id
        store.save
        redirect_to store_path(store.id)
    end

    def show
        @store = Store.find(params[:id])
        @items = @store.items.paginate(:page => params[:page])
    end
     
    def edit
        @store = Store.find(params[:id])
    end

    def update
        store = Store.find(params[:id])
        store.update(name: params[:store][:name])
        store.save
        redirect_to store_path(store.id)
    end

    def destroy
        Store.destroy(params[:id])
        redirect_to stores_path
    end

    private

    def store_params
        params.require(:store).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= form_with model: @categories, local: true do |form| %>
    <div>
        <%= form.label (:name) %>
        <%= form.text_field(:name) %>
    </div>
    <div>
        <%= form.submit("Update") %>
    </div>
<% end %>
<p><%= link_to "Cancel", categories_path %> </p>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% if user_signed_in? && current_user.has_role?(:admin) %>
<p><%= link_to "Create a new category", categories_new_path %></p>
<% end %>

<table>
    <% @categories.each do |cat| %>
        <tr>
            <td>
                <p><%= link_to cat.name, category_path(cat.id) %></p>
            </td>
            <% if user_signed_in? && current_user.has_role?(:admin) %>
                <td>
                    <p><%= link_to "Edit", categories_edit_path(cat.id) %> </p>
                </td>
                <td>
                    <p><%= link_to "Delete", destroy_categories_path(cat.id), method: "delete" %> </p>
                </td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= form_with model: @categories, local: true do |form| %>
    <div>
        <%= form.label (:name) %>
        <%= form.text_field(:name) %>
    </div>
    <div>
        <%= form.submit("Create") %>
    </div>
<% end %>
<p><%= link_to "Cancel", categories_path %> </p>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<!-- category show page -->

<!-- list all items from current category -->
<div class="container">
    <% @items.each do |item| %>
        <div class="item" id="index_item">
            <% if item.image.attached? %>
                <div>
                    <%= cl_image_tag(item.image.key, crop: :scale, width: 200, cloud_name: "dsrp2dd5i") %>
                </div>
            <% end %>
            <div class="container">
                <div class="item">
                    <h5><%= link_to item.title, item_path(item.id) %></h5>
                </div>
                <div class="item">
                    <h3>$<%= "%.2f" % item.price %></h3>
                </div>
            </div>
        </div>
    <% end %>
</div>
<div>
    <%= will_paginate @items %>
</div>

app/views/items/cancel.html.erb
<p>The transaction has been cancelled.</p>

<%= link_to "Back to home", items_path %>

app/views/items/edit.html.erb
<h1>Edit listing</h1>

<%= form_with model: @item, local: true do |form| %>
    <div>
        <%= form.label (:title) %>
        <%= form.text_field(:title) %>
    </div>
    <div>
        <%= form.label (:price) %>
        <%= form.number_field(:price) %>
    </div>
    <div>
        <%= form.label (:category_id) %>
        <%= form.collection_select :category_id, Category.all, :id, :name %>
    </div>
    <div>
        <%= form.label (:description) %>
        <%= form.text_area(:description) %>
    </div>
    <div>
        <%= form.label (:image) %>
        <%= form.file_field (:image) %>
    </div>
    <div>
        <%= form.submit("Update") %>
    </div>
<% end %>

app/views/items/index.html.erb
<!-- items index -->
<p>
    <%= link_to "Create a new listing", items_new_path %>
</p>

<!-- show all listings from all stores -->
<div class="container">
    <% @items.each do |item| %>
        <div class="item" id="index_item">
            <% if item.image.attached? %>
                <div>
                    <%= cl_image_tag(item.image.key, crop: :scale, width: 200, cloud_name: "dsrp2dd5i") %>
                </div>
            <% end %>
            <div class="container">
                <div class="item">
                    <h5><%= link_to item.title, item_path(item.id) %></h5>
                </div>
                <div class="item">
                    <h3>$<%= "%.2f" % item.price %></h3>
                </div>
            </div>
        </div>
    <% end %>
</div>
<div>
    <%= will_paginate @items %>
</div>

app/views/items/new.html.erb
<h1>Create a new listing</h1>

<%= form_with model: @item, local: true do |form| %>
    <div>
        <%= form.label (:title) %>
        <%= form.text_field(:title) %>
    </div>
    <div>
        <%= form.label (:price) %>
        <%= form.number_field(:price) %>
    </div>
    <div>
        <%= form.label (:category_id) %>
        <%= form.collection_select :category_id, Category.all, :id, :name %>
    </div>
    <div>
        <%= form.label (:description) %>
        <%= form.text_area(:description) %>
    </div>
    <div>
        <%= form.label (:image) %>
        <%= form.file_field (:image) %>
    </div>
    <div>
        <%= form.submit("Create") %>
    </div>
<% end %>

app/views/items/show.html.erb
<!-- item show page -->
<div class="container">
    <% if @item.image.attached? %>
        <div class="item" id="img">
            <%= image_tag @item.image, width: 700 %>
        </div>
    <% end %>
    <div class="item">
        <div class="container">
            <div class="item" id="buy">
                <div>
                    <% if user_signed_in? && current_user.id == @item.store.user_id %>
                        <%= link_to "Edit item", edit_item_path %> | 
                        <%= link_to "Delete item", destroy_item_path, method: :delete %> | 
                    <% end %>
                    <%= link_to "Back to results", items_path %>
                </div>
                <div>
                    <h1><%= @item.title %></h1>
                </div>
                <div class="container">
                    <div class="item">
                        <h3>$<%= "%.2f" % @item.price %></h3>
                    </div>
                    <% if user_signed_in? %>
                    <aside class="item">
                        <button id="buynow-button">Buy now</button>
                        <script src="https://js.stripe.com/v3/"></script>
                        <script>
                            const stripe = Stripe('<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>')
                            const buyButton = document.getElementById('buynow-button')
                            buyButton.addEventListener('click', function() {
                                fetch('<%= buy_path(@item.id) %>', {
                                    method: 'POST'
                                })
                                .then(function(response) {
                                    return response.json()
                                })
                                .then(function(session) {
                                    return stripe.redirectToCheckout({ sessionId: session.id })
                                })
                                })
                        </script>
                    </aside>
                    <% elsif %>
                        <aside>
                            <p>You must be logged in to make a purchase.</p>
                        </aside>
                    <% end %>
                </div>
            </div>
            <aside class="item" id="seller">
                <p>Sold by:</p>
                <h3><%= @item.store.user.email %></h3>
            </aside>
            
        </div>
        <div class="item" id="desc">
            <%= @item.description %>
        </div>
    </div>
</div>

app/views/items/success.html.erb
<p>Success! Thank you for your purchase.</p>

<%= link_to "Back to home", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apsales</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav>
      <div class="container">
        <div class="item">
          <span><%= link_to "Categories", categories_path %> | 
            <%= link_to "Stores", stores_path %> | 
            <%= link_to "View all items", items_path %></span>
        </div>
        <div class="container">
          <% if !user_signed_in? %>
            <%= link_to "Sign up", new_user_registration_path %> 
            <span> &nbsp;&nbsp;|&nbsp;&nbsp; </span>
            <%= link_to "Sign in", new_user_session_path %>
          <% end %>
          <% if user_signed_in? %>
            <span>Welcome, <%= current_user.email %>!
            <%= link_to "Sign out", destroy_user_session_path, method: "delete" %></span>
          <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>gg</h1>

<!-- redirects to items index -->

app/views/stores/edit.html.erb
<h1>Edit store name</h1>

<%= form_with model: @store, local: true do |form| %>
    <%= form.label(:name) %>
    <%= form.text_field(:name) %>
    <%= form.submit("Update") %>
<% end %>

app/views/stores/index.html.erb
<h1>All stores</h1>

<p><%= link_to "Create a new store", stores_new_path %></p>

<% @stores.each do |store| %>
    <p><%= link_to store.name, store_path(store.id)%></p>
<% end %>

app/views/stores/new.html.erb
<h1>create a store</h1>
    <%= form_with model: @store, local: true do |form| %>
        <%= form.label (:name) %>
        <%= form.text_field(:name) %>
        <%= form.submit("Create") %>
    <% end %>

app/views/stores/show.html.erb
<!-- show store page -->

<table>
    <tr>
        <td>Store name: <%= @store.name %></td>
    </tr>
    <% if current_user.id == @store.user_id %>
        <tr>
            <td><%= link_to "Edit store name", edit_path %></td>
            <td><%= link_to "Delete store", destroy_store_path, method: "delete"  %></td>
            <td><%= link_to "Create a listing", items_new_path %></td>
        </tr>
    <% end %>
</table>
<div class="container">
    <% @items.each do |item| %>
        <div class="item" id="index_item">
            <% if item.image.attached? %>
                <div>
                    <%= cl_image_tag(item.image.key, crop: :scale, width: 200, cloud_name: "dsrp2dd5i") %>
                </div>
            <% end %>
            <div class="container">
                <div class="item">
                    <h5><%= link_to item.title, item_path(item.id) %></h5>
                </div>
                <div class="item">
                    <h3>$<%= "%.2f" % item.price %></h3>
                </div>
            </div>
        </div>
    <% end %>
</div>
<div>
    <%= will_paginate @items %>
</div>